# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

jobs:
  - job: publish
    displayName: publish
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Npm@1
        inputs:
          versionSpec: '12.x'
      - bash: TAG=$(Build.SourceBranch) ./scripts/publish.js
        displayName: runscript
